apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang-nodeport
  name: golang-nodeport
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  selector:
    app: golang-dep
  type: NodePort
status:
  loadBalancer: {}
